#!/bin/env python
import json, getopt, os.path, sys
# import httplib2, webbrowser

# from oauth2client import client
# from oauth2client.file import Storage
# from google.oauth2.credentials import Credentials

blogId = os.getenv("blog") # put your blog ID here
isDraft = True # Don't change this unless you are prepared to modify the script
postfile = ''
title = 'Minha nova postagem' # Change this to the default title you prefer
postId = ''

# comma delimited list of labels for the post.
# If you set a default list it will be overwritten
# if labels are supplied in the command line args
# otherwise the default list is used
labels = 'mac os x, blogger, CLI'

# At a minimum we must include the file containing our blog post
if(len(sys.argv) < 2):
	print("""Usage: %s
	list
	view 1
	create -f \"Filename\" [-t] \"My Title\" [-l] \"label,label\" [--publish]
	edit 1 -f \"Filename\" [-t] \"My Title\" [-l] \"label,label\" [--publish]
			 """ % sys.argv[0])
	print("Post's are uploaded as drafts by default. Use --publish if you want to "
			"publish immediatly\n")
	sys.exit()
 
# Handle arguments
myopts, args = getopt.getopt(sys.argv[1:], "f:t:l:p:", ['publish'])
for o, a in myopts:
	if o == '-f':
		postfile = a
	elif o == '--publish':
		isDraft = False
	elif o == '-t':
		title = a
	elif o == '-l':
		labels = a
	elif o == '-p':
		postId = a

if len(args) < 1:
	print("action missing list view etc")

action = args[0]

if action in ("edit", "view"):
	if len(args) < 2:
		print("post number missing eg 1 2 3")
		exit(1)
	post = args[1]

# If we want to publish we must supply a title
if(isDraft == False and title == 'Minha nova postagem'):
	print("You must provide a title if you want to publish")
	sys.exit()

# Open file for reading
if action in ("create", "edit"):
	f = open(postfile, 'r')

	#build a label list
	labels_list = labels.split(',')

	#build body object
	body = {
			"content": f.read(),
			"title": title,
			"labels": labels_list
			}

# If there is no userkey authenticate with Google and save the key.
if True:
# if False:
	pass

	# credentials = Credentials(
	# 	token=os.getenv("token"),
	# 	quota_project_id=os.getenv("project"),
	# 	)

elif(os.path.exists('userkey') == False):
	flow = client.flow_from_clientsecrets('client_id.json',
										  scope='https://www.googleapis.com/auth/blogger',
										  redirect_uri='urn:ietf:wg:oauth:2.0:oob'
										  )

	auth_uri = flow.step1_get_authorize_url()
	webbrowser.open_new(auth_uri)
	auth_code = raw_input('Enter the auth code: ')
	credentials = flow.step2_exchange(auth_code)
	http_auth = credentials.authorize(httplib2.Http())

	# Store the credentials
	storage = Storage('userkey')
	storage.put(credentials)

# If the userkey already exists use it.
else:
	storage = Storage('userkey')
	credentials = storage.get()
	# http_auth = credentials.authorize(httplib2.Http())

# Initialize the blogger service and get the blog
from apiclient.discovery import build
# blogger_service = build('blogger', 'v3', http=http_auth)
# service = build('blogger', 'v3', credentials=credentials)
service = build('blogger', 'v3')

# user_info = blogger_service.users().get(userId='self').execute()
# print(user_info)
# exit()

if blogId == None:
	blogs = service.blogs()
	myblogs = blogs.listByUser(userId='self').execute()
	for blog in myblogs['items']:
		# print(blog)
		# print('The blog named \'%s\' is at: %s' % (blog['name'], blog['url']))
		blogId = blog["id"]
	# exit()


# if(os.path.exists('postId') == False):
# 	try:
# 	post = blogger_service.posts().insert(blogId=blogId, body=body, isDraft=isDraft).execute()
# 	except:
# 		print("Something went wrong uploading this post")
# 		sys.exit()

# print (args)
# exit()

if action == "list":
	print(args)

if action == "view":
	print(args)

if action == "create":
#Insert the post
	post = blogger_service.posts().insert(blogId=blogId, body=body, isDraft=isDraft).execute()

	print("Title: %s" % post['title'])
	print("Is Draft: %s" % isDraft)
	print("Post ID: %s" % post['id'])
	if(isDraft == False):
		print("URL: %s" % post['url'])
	print("Labels: %s" % post['labels'])

if action == "edit":
	post = service.posts().update(blogId=blogId, postId=postId, body=body, publish=True).execute()
		
	print("Title: %s" % post['title'])
	print("URL: %s" % post['url'])
	print("Labels: %s" % post['labels'])	
